url: https://kydara.github.io/Andromeda/
author: Peacemaker
title: Kydara Status
description: Kydara systems status at a glance!
homepage: https://yourcompany.name

permalink: pretty
uptime_days: 60

# TODO: Build pagination into archive
plugins: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'
