url: https://kydara.github.io/Andromeda/
author: Example Author
email: support@example.com
title: Andromeda
description: Jekyll-based status page.
homepage: https://yourcompany.name

permalink: pretty
uptime_days: 60

# TODO: Build pagination into archive
plugins: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'
