url: https://kydara.github.io/Andromeda
author: Peacemaker
title: Andromeda
description: System status at a glance
homepage: https://www.example.com
homepage_name: Andromeda Home

feed:
  path: atom.xml

permalink: pretty

# TODO: Build pagination into archive
plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 2
paginate_path: '/archive/page:num/'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"